# Generated by Django 2.2.7 on 2019-12-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votedata', '0002_auto_20191207_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='userprofile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='votedata.Profile'),
            preserve_default=False,
        ),
    ]
