# Generated by Django 2.2.7 on 2019-12-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votedata', '0005_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user.png', upload_to='profile_pics'),
        ),
    ]
