# Generated by Django 2.2.7 on 2019-12-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votedata', '0007_auto_20191212_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='type',
            field=models.CharField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Unknown')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voting',
            name='mode',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
