# Generated by Django 2.2.7 on 2019-12-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votedata', '0010_auto_20191215_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='mode',
            field=models.CharField(choices=[('o', 'One choice'), ('m', 'Multiple choice')], default=0, max_length=50),
        ),
    ]
