# Generated by Django 2.2.7 on 2019-12-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votedata', '0011_auto_20191215_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='theme',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
