# Generated by Django 2.2.7 on 2019-12-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votedata', '0012_voting_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='need_password',
        ),
    ]
